name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clear actions cache
        run: |
          rm -rf ~/.npm
          rm -rf ~/.cache

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Verify Node.js installation
        run: node --version

      - name: Verify npm installation
        run: npm --version

      - name: List project root directory contents
        run: ls -la

      - name: List JSON directory contents
        run: ls -la json

      - name: Build with Maven
        run: mvn clean install

      - name: Verify Safari installation
        run: |
          safaridriver --version
